name: Ivan Huang
avatar: https://gravatar.loli.net/avatar/5cad7e9fe5a1ff8e50363b833e1c5b84?s=400
title: Software Engineer
links:
  - label: About
    icon: fa-user-circle
    url: https://notes.ivanhjc.net/about
  - label: Github
    icon: brands fa-github
    url: https://github.com/ivanhjc
  - label: StackExchange
    icon: brands fa-stack-exchange
    url: https://stackexchange.com/users/4773526/ivan-huang    
  - label: Twitter
    icon: brands fa-twitter
    url: https://twitter.com/ivanhjc_
