name: Ivan Huang
avatar: https://res.cloudinary.com/ivanhjc/image/upload/v1602736588/lADPBG1Q53OmyVjNCmzNCmw_2668_2668_rxbufo.jpg
title: Senior Software Engineer
links:
  - label: About
    icon: fa-user-circle
    url: https://notes.ivanhjc.net
  - label: Github
    icon: brands fa-github
    url: https://github.com/ivanhjc
  - label: Twitter
    icon: brands fa-twitter
    url: https://twitter.com/ivanhjc_
